# Generated by Django 3.2.20 on 2023-08-30 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='period',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
